<?php

namespace TechSuite\PublicBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{



	public function findOneByIdJoinedToOffices($id)
	{
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT c, o FROM TechSuitePublicBundle:Contact c
	            JOIN c.offices o
	            WHERE c.id = :id'
	        )->setParameter('id', $id);

	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}



}


