<?php

namespace TechSuite\PublicBundle\Repository;

/**
 * OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends \Doctrine\ORM\EntityRepository
{


	public function findOneByIdJoinedToContacts($id)
	{
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT o, c FROM TechSuitePublicBundle:Office o
	            JOIN o.contacts c
	            WHERE o.id = :id'
	        )->setParameter('id', $id);

	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}


}


